services:
  counter:
    build: ./counter
    ports:
      - "3000:3001"
    image: counter:1.0 
    environment:
      REDIS_HOST: redis
      NOTICE_BOARD_NAME: "CST notice board"
    depends_on:
      redis: 
        condition: service_healthy
    restart: unless-stopped
    
  redis: 
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: unless-stopped 
  
  notice: 
    build: ./notice
    ports: 
     - "3002:80"
    restart: unless-stopped
    image: notice:1.0
    
volumes:
  redis_data: 
